const coursesData = [
    {
        title: "دورة اساسيات البرمجة واحتراف لغة بايثون",
        description: "اكتسب مهارات البرمجة الأساسية، وتعلم مبادئ هندسة البرمجيات من الصفر، في رحلة تعلم تتميز بالتطبيق العملي والمشاريع الحقيقية والدعم المستمر.",
        link: "https://www.codezilla.courses/introduction-to-programming/?coupon=ELZERO",
        category: "Web Development",
        language: "Arabic",
        cost: "Paid",
    },
    {
        title: "دورة تطوير التطبيقات باستخدام فلاتر",
        description: "تعلم كيفية إنشاء تطبيقات متعددة الأنظمة باستخدام فلاتر ولغة دارت.",
        link: "https://mystro-learning.com/",
        category: "Mobile App Development",
        language: "Arabic",
        cost: "Free and Paid",
    },
    {
        title: "دورة تطوير البرمجيات بلغة Java",
        description: "مسار كامل لتعلم لغة جافا من الأساسيات إلى الاحتراف، مع التركيز على التطبيقات العملية.",
        link: "https://mystro-learning.com/",
        category: "Desktop App Development",
        language: "Arabic",
        cost: "Free and Paid",
    },
    {
        title: "دورة تعلم HTML وCSS وJavaScript",
        description: "تعلم أساسيات تطوير الويب باستخدام اللغات الثلاثة الأساسية.",
        link: "http://www.w3arabiconline.com",
        category: "Web Development",
        language: "Arabic",
        cost: "Free",
    },
    {
        title: "دورة تحليل البيانات باستخدام بايثون",
        description: "تعلم كيفية استخدام بايثون لتحليل البيانات ومعالجتها.",
        link: "https://www.codezilla.courses/",
        category: "Data Science",
        language: "Arabic",
        cost: "Paid",
    },
    {
        title: "دورة أمان المعلومات (Cybersecurity)",
        description: "تعلم كيفية حماية الأنظمة والمعلومات من التهديدات.",
        link: "http://www.w3arabiconline.com",
        category: "Cybersecurity",
        language: "Arabic",
        cost: "Paid",
    },
    {
        title: "دورة تصميم واجهات المستخدم باستخدام فلاتر",
        description: "تعلم كيفية تصميم واجهات مستخدم جذابة لتطبيقات الهاتف.",
        link: "https://mystro-learning.com/",
        category: "Design",
        language: "Arabic",
        cost: "Paid",
    },
    {
        title: "دورة برمجة الألعاب باستخدام Unity",
        description: "تعلم كيفية تطوير الألعاب باستخدام محرك Unity.",
        link: "http://www.w3arabiconline.com",
        category: "Game Development",
        language: "Arabic",
        cost: "Paid",
    },
    {
        title: "دورة إدارة قواعد البيانات باستخدام SQL",
        description: "تعلم كيفية إدارة قواعد البيانات باستخدام SQL.",
        link: "http://www.w3arabiconline.com",
        category: "Database Management",
        language: "Arabic",
        cost: "Free and Paid",
    },
    {
        title: "دورة تطوير تطبيقات الويب باستخدام Django",
        description: "تعلم كيفية بناء تطبيقات الويب باستخدام إطار العمل Django.",
        link: "https://www.codezilla.courses/",
        category: "Web Development",
        language: "Arabic",
        cost: "Paid",
    },
    {
        title: "دورة تطوير التطبيقات باستخدام فلاتر ودارت",
        description: "تعلم كيفية بناء تطبيقات تعمل على أنظمة متعددة باستخدام فلاتر ودارت.",
        link: "https://www.udemy.com/course/the-complete-2022-flutter-dart-development-course-arabic/",
        category: "Mobile App Development",
        language: "Arabic",
        cost: "Paid"
    },
    {
        title: "الدورة الشاملة لتطوير الويب باللغة العربية 2024",
        description: "مسار شامل لتعلم تطوير الويب من البداية إلى الاحتراف، مع التركيز على تحويل تطبيقات الويب إلى تطبيقات موبايل وسطح المكتب.",
        link: "https://arabicoders.com/courses/",
        category: "Web Development",
        language: "Arabic",
        cost: "Paid"
    },
    {
        title: "دورة الجافا سكريبت الكاملة بالتطبيقات العملية",
        description: "تعلم لغة JavaScript من الأساس إلى التطبيقات العملية.",
        link: "https://arabicoders.com/courses/",
        category: "Web Development",
        language: "Arabic",
        cost: "Paid"
    },
    {
        title: "Master Java SpringBoot & Microservices",
        description: "دورة متقدمة في تطوير البرمجيات باستخدام Java مع التركيز على Spring Boot وMicroservices.",
        link: "https://arabicoders.com/courses/",
        category: "Software Development",
        language: "Arabic",
        cost: "Paid"
    },
    {
        title: "دورة تحليل البيانات باستخدام بايثون",
        description: "تعلم كيفية تحليل ومعالجة البيانات باستخدام لغة بايثون.",
        link: "https://gammal.tech/courses",
        category: "Data Science",
        language: "Arabic",
        cost: "Paid"
    },
    {
        title: "دورة تطوير الويب باستخدام PHP و MySQL",
        description: "تعلم كيفية تطوير الويب باستخدام PHP و MySQL لبناء تطبيقات ويب ديناميكية.",
        link: "https://arabicoders.com/courses/",
        category: "Web Development",
        language: "Arabic",
        cost: "Paid"
    },
    {
        title: "كورس جافا سكريبت الكامل",
        description: "كورس شامل حول JavaScript مع التطبيقات العملية.",
        link: "https://www.arabicoders.com",
        category: "Web Development",
        language: "Arabic",
        cost: "$129.99"
    },
    {
        title: "دورة برمجة C++ للمبتدئين",
        description: "كورس شامل للمبتدئين في لغة البرمجة C++.",
        link: "https://www.youtube.com",
        category: "Programming (C++)",
        language: "Arabic",
        cost: "Free"
    },
    {
        title: "دورة AWS Certified Solutions Architect - Associate",
        description: "كورس حول حلول AWS المعتمدة من المهندس عيسى أبو شريف.",
        link: "https://www.youtube.com",
        category: "Cloud Computing",
        language: "Arabic",
        cost: "Free"
    },
    {
        title: "كورس CS50 بالعربي",
        description: "كورس علوم الحاسب الشهير من جامعة هارفارد باللغة العربية.",
        link: "https://www.youtube.com",
        category: "Computer Science",
        language: "Arabic",
        cost: "Free"
    },
    {
        title: "دورة البرمجة بلغة C# مع اختبار الوحدات",
        description: "كورس حول البرمجة بلغة C# واختبار الوحدات.",
        link: "https://www.youtube.com",
        category: "Programming (C#)",
        language: "Arabic",
        cost: "Free"
    },
    {
        title: "دورة أتمتة الاختبارات باستخدام Selenium",
        description: "دورة شاملة لتعلم أتمتة اختبارات الويب باستخدام Selenium.",
        link: "https://www.coursera.org/arabic-programming",
        category: "Testing & Automation",
        language: "Arabic",
        cost: "Paid"
    },
    {
        title: "دورة إدارة المشاريع البرمجية باستخدام Jira",
        description: "تعلم كيفية إدارة المشاريع التقنية باستخدام Jira ومنهجية Scrum.",
        link: "https://www.coursera.org/",
        category: "Project Management",
        language: "Arabic",
        cost: "Free & Paid"
    },
    {
        title: "دورة تطوير تطبيقات الهاتف باستخدام React Native",
        description: "تعلم كيفية بناء تطبيقات الهواتف متعددة المنصات باستخدام React Native.",
        link: "https://gammal.tech/courses",
        category: "Mobile App Development",
        language: "Arabic",
        cost: "Paid"
    },
    {
        title: "دورة تحليل البيانات المتقدم باستخدام Pandas وNumpy",
        description: "دورة متقدمة لتحليل البيانات باستخدام مكتبات Pandas وNumpy في بايثون.",
        link: "https://gammal.tech/courses",
        category: "Data Science",
        language: "Arabic",
        cost: "Paid"
    },
    {
        title: "دورة الذكاء الاصطناعي وتعلم الآلة",
        description: "دورة حول الذكاء الاصطناعي وتعلم الآلة باستخدام بايثون.",
        link: "https://github.com/free-programming-books",
        category: "AI & Machine Learning",
        language: "Arabic",
        cost: "Free"
    },
    //tesssssssssssssssssssssssssssssssssst
    {
        title: "دورة اساسيات البرمجة واحتراف لغة بايثون",
        description:
            "اكتسب مهارات البرمجة الأساسية، وتعلم مبادئ هندسة البرمجيات من الصفر، في رحلة تعلم تتميز بالتطبيق العملي والمشاريع الحقيقية والدعم المستمر، لتتمكن من التعمق في اهم مجالات البرمجة بكل ثقة",
        link: "https://www.codezilla.courses/introduction-to-programming/?coupon=ELZERO",
        category: "Web Development",
        language: "Arabic",
        cost: "Paid",
    },
    {
        title: "إنشاء 50 تطبيق عملي على لغة جافاسكربت",
        description:
            "إنشاء 50 تطبيق عملي على لغة جافاسكربت لتوظيف ما تعلمته في مجالك Front-End Developer",
        link: "https://www.elzero.courses/create-50-javascript-applications",
        category: "Web Development",
        language: "Arabic",
        cost: "Paid",
    },
    {
        title: "Web Design for Web Developers: Build Beautiful Websites!",
        description:
            "Learn web design in 1 hour with 25+ simple-to-use rules and guidelines — tons of amazing web design resources included!",
        link: "https://www.udemy.com/course/web-design-secrets/",
        category: "Web Development",
        language: "English",
        cost: "Paid",
        instructor: "Daniel Scott",
    },
    {
        title: "Advanced CSS and Sass: Flexbox, Grid, Animations and More!",
        description:
            "The most advanced and modern CSS course on the internet: master flexbox, CSS Grid, responsive design, and so much more.",
        link: "https://www.udemy.com/course/advanced-css-and-sass/?couponCode=2021PM25",
        category: "Web Development",
        language: "English",
        cost: "Paid",
        instructor: "Jonas Schmedtmann",
    },
    {
        title: "Crash Course: Build a Full-Stack Web App in a Weekend!",
        description:
            "A quick, fun, and hands-on introduction to web development. Build a complete app with HTML, CSS, JavaScript, and React!",
        link: "https://www.udemy.com/course/full-stack-crash-course/",
        category: "Web Development",
        language: "English",
        cost: "Paid",
        instructor: "Brad Traversy",
    },
    {
        title: "Node.js, Express, MongoDB & More: The Complete Bootcamp",
        description:
            "Master Node by building a real-world RESTful API and web app (with authentication, Node.js security, payments & more)",
        link: "https://www.udemy.com/course/nodejs-express-mongodb-bootcamp/",
        category: "Web Development",
        language: "English",
        cost: "Paid",
        instructor: "Jose Portilla",
    },
    {
        title: "Build Responsive Real-World Websites with HTML and CSS",
        description:
            "Learn modern HTML5, CSS3 and web design by building a stunning website for your portfolio! Includes flexbox and CSS Grid",
        link: "https://www.udemy.com/course/design-and-develop-a-killer-website-with-html5-and-css3/",
        category: "Web Development",
        language: "English",
        cost: "Paid",
        instructor: "Jonas Schmedtmann",
    },
    {
        title: "The Complete JavaScript Course 2024: From Zero to Expert!",
        description:
            "The modern JavaScript course for everyone! Master JavaScript with projects, challenges and theory. Many courses in one!",
        link: "https://www.udemy.com/course/the-complete-javascript-course/",
        category: "Web Development",
        language: "English",
        cost: "Paid",
        instructor: "Jonas Schmedtmann",
    },
    {
        title: "The Ultimate React Course 2024: React, Next.js, Redux & More",
        description:
            "Master modern React from beginner to advanced! Next.js, Context API, React Query, Redux, Tailwind, advanced patterns",
        link: "https://www.udemy.com/course/the-ultimate-react-course/",
        category: "Web Development",
        language: "English",
        cost: "Paid",
        instructor: "Mosh Hamedani",
    },
    {
        title: "Mobile App Development with Flutter & Dart",
        description:
            "Learn to build beautiful, fast, and native mobile apps with Flutter & Dart. Covers everything from basics to advanced features.",
        link: "https://www.udemy.com/course/learn-flutter-dart-to-build-ios-android-apps/",
        category: "Mobile App Development",
        language: "English",
        cost: "Paid",
        instructor: "Maximilian Schwarzmüller",
    },
    {
        title: "iOS 17 & SwiftUI - The Complete iOS App Development Bootcamp",
        description:
            "Build real-world iOS apps with SwiftUI & Swift 5. Learn from scratch and become a professional iOS developer.",
        link: "https://www.udemy.com/course/ios-13-app-development-bootcamp/",
        category: "Mobile App Development",
        language: "English",
        cost: "Paid",
        instructor: "Angela Yu",
    },
    {
        title: "The Complete React Native + Hooks Course [2024 Edition]",
        description:
            "Learn React Native and Hooks from scratch. Build real-world mobile apps with React Native and improve your skills.",
        link: "https://www.udemy.com/course/react-native-the-practical-guide/",
        category: "Mobile App Development",
        language: "English",
        cost: "Paid",
        instructor: "Maximilian Schwarzmüller",
    },
    {
        title: "Desktop Application Development with Electron",
        description:
            "Build cross-platform desktop apps with Electron. Learn to create powerful desktop applications using web technologies.",
        link: "https://www.udemy.com/course/electron-react/",
        category: "Desktop App Development",
        language: "English",
        cost: "Paid",
        instructor: "Stephen Grider",
    },
    {
        title: "Introduction to Desktop Application Development with Java",
        description:
            "Learn to create desktop applications using Java. Explore the fundamentals of JavaFX and Swing for desktop development.",
        link: "https://www.udemy.com/course/javafx-tutorial/",
        category: "Desktop App Development",
        language: "English",
        cost: "Paid",
        instructor: "David Katz",
    },
    {
        title: "Game Development with Unity: Ultimate Guide",
        description:
            "Master Unity and C# to create your own games. Comprehensive guide to game development from beginner to advanced.",
        link: "https://www.udemy.com/course/unitycourse/",
        category: "Game Development",
        language: "English",
        cost: "Paid",
        instructor: "Ben Tristem",
    },
    {
        title: "Complete C# Unity Game Developer 2D",
        description:
            "Learn to build 2D games with Unity and C#. This course covers everything from game design principles to publishing.",
        link: "https://www.udemy.com/course/unity-game-development/",
        category: "Game Development",
        language: "English",
        cost: "Paid",
        instructor: "GameDev.tv by Rick & Ben",
    },
    {
        title: "Database Management Essentials: SQL & NoSQL",
        description:
            "Learn essential database management skills with SQL and NoSQL. Covers database design, querying, and management.",
        link: "https://www.udemy.com/course/database-management-sql-nosql/",
        category: "Database Management",
        language: "English",
        cost: "Paid",
        instructor: "Luis Sanchez",
    },
    {
        title: "MongoDB - The Complete Developer's Guide",
        description:
            "Comprehensive guide to MongoDB. Learn MongoDB from scratch and use it in full-stack applications.",
        link: "https://www.udemy.com/course/mongodb-the-complete-developers-guide/",
        category: "Database Management",
        language: "English",
        cost: "Paid",
        instructor: "Maximilian Schwarzmüller",
    },
    {
        title: "Learn SQL Basics for Data Science",
        description:
            "An introductory course on SQL for data science. Learn how to use SQL for data analysis and management.",
        link: "https://www.coursera.org/learn/sql-for-data-science",
        category: "Database Management",
        language: "English",
        cost: "Free",
        instructor: "Danielle McCormick",
    },
    // Added Courses
    {
        title: "The Web Developer Bootcamp",
        description:
            "A comprehensive bootcamp for web development, covering HTML, CSS, JavaScript, Node.js, and more.",
        link: "https://www.udemy.com/course/the-web-developer-bootcamp/",
        category: "Web Development",
        language: "English",
        cost: "Paid",
        instructor: "Colt Steele",
    },
    {
        title: "Complete Guide to Angular: Angular 15+",
        description:
            "Master Angular with this comprehensive course, including Angular 15 and advanced topics.",
        link: "https://www.udemy.com/course/the-complete-guide-to-angular/",
        category: "Web Development",
        language: "English",
        cost: "Paid",
        instructor: "Maximilian Schwarzmüller",
    },
    {
        title: "Vue JS - The Complete Guide (w/ Router, Vuex, Composition API)",
        description:
            "Master Vue.js by building real applications with the latest version of Vue.js including Vue Router and Vuex.",
        link: "https://www.udemy.com/course/vuejs-2-the-complete-guide/",
        category: "Web Development",
        language: "English",
        cost: "Paid",
        instructor: "Maximilian Schwarzmüller",
    },
    {
        title: "Mastering Python for Data Science and Machine Learning",
        description:
            "Learn Python for data science and machine learning. Master the essential libraries and techniques.",
        link: "https://www.udemy.com/course/machinelearning/",
        category: "Data Science",
        language: "English",
        cost: "Paid",
        instructor: "Jose Portilla",
    },
    {
        title: "Introduction to TensorFlow for Artificial Intelligence, Machine Learning, and Deep Learning",
        description:
            "Learn to build neural networks and deep learning models using TensorFlow.",
        link: "https://www.coursera.org/learn/introduction-tensorflow",
        category: "Data Science",
        language: "English",
        cost: "Free",
        instructor: "Laurence Moroney",
    },
    {
        title: "Python for Data Science and Machine Learning Bootcamp",
        description:
            "Learn how to use Python for data science and machine learning in this comprehensive bootcamp.",
        link: "https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/",
        category: "Data Science",
        language: "English",
        cost: "Paid",
        instructor: "Jose Portilla",
    },
    {
        title: "Data Science and Machine Learning with Python",
        description:
            "A comprehensive course on data science and machine learning using Python and its powerful libraries.",
        link: "https://www.udemy.com/course/data-science-and-machine-learning-with-python-hands-on/",
        category: "Data Science",
        language: "English",
        cost: "Paid",
        instructor: "Frank Kane",
    },
    {
        title: "Artificial Intelligence: Foundations of Computational Agents",
        description:
            "Learn the foundations of AI and how to build intelligent agents in Python.",
        link: "https://www.coursera.org/learn/ai-foundations",
        category: "Data Science",
        language: "English",
        cost: "Free",
        instructor: "David Silver",
    },
    {
        title: "Machine Learning A-Z™: Hands-On Python & R In Data Science",
        description:
            "Learn how to create machine learning algorithms in Python and R from scratch.",
        link: "https://www.udemy.com/course/machinelearningaz/",
        category: "Data Science",
        language: "English",
        cost: "Paid",
        instructor: "Kirill Eremenko",
    },
    {
        title: "The Complete Machine Learning and Data Science Bootcamp",
        description:
            "Learn machine learning, data science, and data analysis using Python, NumPy, and Pandas.",
        link: "https://www.udemy.com/course/the-complete-machine-learning-course/",
        category: "Data Science",
        language: "English",
        cost: "Paid",
        instructor: "Andrew Ng",
    },
    // Adding 60 Arabic courses
    {
        title: "دورة تطوير واجهات المستخدم باستخدام فريمورك فلوتر",
        description: "تعلم كيفية تطوير واجهات المستخدم باستخدام فلوتر، مع تطبيقات عملية ومشاريع حقيقية.",
        link: "https://www.udemy.com/course/flutter-ui-development/",
        category: "Mobile App Development",
        language: "Arabic",
        cost: "Paid",
        instructor: "محمد علي",
    },
    {
        title: "دورة كاملة في علم البيانات باستخدام بايثون",
        description: "تعلم تحليل البيانات وبناء نماذج تعلم الآلة باستخدام بايثون.",
        link: "https://www.udemy.com/course/data-science-with-python-ar/",
        category: "Data Science",
        language: "Arabic",
        cost: "Paid",
        instructor: "أحمد سعيد",
    },
    {
        title: "دورة تطوير تطبيقات الويب باستخدام جافاسكربت",
        description: "تعلم تطوير تطبيقات الويب من الصفر باستخدام جافاسكربت.",
        link: "https://www.udemy.com/course/web-development-with-javascript-ar/",
        category: "Web Development",
        language: "Arabic",
        cost: "Paid",
        instructor: "ليلى حسين",
    },
    {
        title: "مقدمة في الذكاء الاصطناعي",
        description: "تعلم أساسيات الذكاء الاصطناعي وتطبيقاته في مختلف المجالات.",
        link: "https://www.udemy.com/course/ai-introduction-ar/",
        category: "Data Science",
        language: "Arabic",
        cost: "Free",
        instructor: "فاطمة الزهراء",
    },
    {
        title: "دورة تطوير التطبيقات باستخدام بايثون",
        description: "تعلم كيفية بناء تطبيقات عملية باستخدام بايثون.",
        link: "https://www.udemy.com/course/python-app-development-ar/",
        category: "Web Development",
        language: "Arabic",
        cost: "Paid",
        instructor: "علي جمال",
    },
    {
        title: "أساسيات البرمجة بلغة جافا",
        description: "تعلم البرمجة بلغة جافا من خلال مشاريع تطبيقية.",
        link: "https://www.udemy.com/course/java-basics-ar/",
        category: "Programming",
        language: "Arabic",
        cost: "Free",
        instructor: "سمير محمد",
    },
    {
        title: "تطوير ألعاب الفيديو باستخدام يونتي",
        description: "احصل على المهارات اللازمة لإنشاء ألعاب الفيديو باستخدام محرك يونتي.",
        link: "https://www.udemy.com/course/unity-video-game-development-ar/",
        category: "Game Development",
        language: "Arabic",
        cost: "Paid",
        instructor: "حسن محمود",
    },
    {
        title: "دورة متكاملة في تطوير واجهات المستخدم",
        description: "تعلم تصميم وتطوير واجهات المستخدم الحديثة.",
        link: "https://www.udemy.com/course/ui-ux-design-ar/",
        category: "Web Development",
        language: "Arabic",
        cost: "Paid",
        instructor: "نور الدين",
    },
    {
        title: "علم البيانات وتعلم الآلة باستخدام بايثون",
        description: "استكشف طرق تحليل البيانات وتطبيقات تعلم الآلة.",
        link: "https://www.udemy.com/course/python-for-data-science-ar/",
        category: "Data Science",
        language: "Arabic",
        cost: "Paid",
        instructor: "محمود عادل",
    },
    {
        title: "دورة بناء تطبيقات الويب باستخدام فريمورك لارافيل",
        description: "تعلم كيفية بناء تطبيقات الويب باستخدام لارافيل.",
        link: "https://www.udemy.com/course/laravel-web-development-ar/",
        category: "Web Development",
        language: "Arabic",
        cost: "Paid",
        instructor: "خالد الشمري",
    },
    {
        title: "إدارة قواعد البيانات باستخدام SQL",
        description: "تعلم كيفية استخدام SQL لإدارة وتحليل البيانات.",
        link: "https://www.udemy.com/course/sql-database-management-ar/",
        category: "Database Management",
        language: "Arabic",
        cost: "Free",
        instructor: "أميرة هاني",
    },
    {
        title: "أساسيات الأمن السيبراني",
        description: "تعلم كيفية حماية المعلومات والأنظمة من التهديدات.",
        link: "https://www.udemy.com/course/cyber-security-fundamentals-ar/",
        category: "Cybersecurity",
        language: "Arabic",
        cost: "Paid",
        instructor: "حسين ياسر",
    },
    {
        title: "مقدمة في تطوير التطبيقات باستخدام React",
        description: "تعلم أساسيات تطوير تطبيقات الويب باستخدام React.",
        link: "https://www.udemy.com/course/react-introduction-ar/",
        category: "Web Development",
        language: "Arabic",
        cost: "Free",
        instructor: "علياء عادل",
    },
    {
        title: "برمجة تطبيقات الهواتف المحمولة باستخدام كوتلن",
        description: "تطوير تطبيقات الهواتف المحمولة باستخدام لغة كوتلن.",
        link: "https://www.udemy.com/course/kotlin-mobile-app-development-ar/",
        category: "Mobile App Development",
        language: "Arabic",
        cost: "Paid",
        instructor: "مريم منصور",
    },
    {
        title: "التسويق الرقمي: استراتيجيات النجاح",
        description: "تعلم أساسيات التسويق الرقمي وأفضل الاستراتيجيات للتسويق.",
        link: "https://www.udemy.com/course/digital-marketing-ar/",
        category: "Marketing",
        language: "Arabic",
        cost: "Paid",
        instructor: "جميلة زكريا",
    },
    {
        title: "تصميم الجرافيك باستخدام Adobe Photoshop",
        description: "تعلم أساسيات تصميم الجرافيك باستخدام برنامج فوتوشوب.",
        link: "https://www.udemy.com/course/photoshop-graphic-design-ar/",
        category: "Design",
        language: "Arabic",
        cost: "Paid",
        instructor: "رامي حسن",
    },
    {
        title: "تطوير تطبيقات الويب باستخدام فريمورك دجانغو",
        description: "تعلم كيفية تطوير تطبيقات الويب باستخدام فريمورك دجانغو.",
        link: "https://www.udemy.com/course/django-web-development-ar/",
        category: "Web Development",
        language: "Arabic",
        cost: "Paid",
        instructor: "زكريا يوسف",
    },
    {
        title: "إدارة مشاريع البرمجة: المنهجية والعمليات",
        description: "تعلم كيفية إدارة مشاريع البرمجة بشكل فعال.",
        link: "https://www.udemy.com/course/project-management-ar/",
        category: "Project Management",
        language: "Arabic",
        cost: "Free",
        instructor: "فريد صبحي",
    },
    {
        title: "مقدمة في تكنولوجيا المعلومات",
        description: "استكشف أساسيات تكنولوجيا المعلومات وتطبيقاتها.",
        link: "https://www.udemy.com/course/it-fundamentals-ar/",
        category: "IT",
        language: "Arabic",
        cost: "Paid",
        instructor: "أحمد سعيد",
    },
    {
        title: "دورة متكاملة في التحليل الإحصائي باستخدام R",
        description: "تعلم التحليل الإحصائي باستخدام لغة R.",
        link: "https://www.udemy.com/course/statistics-analysis-ar/",
        category: "Data Science",
        language: "Arabic",
        cost: "Paid",
        instructor: "جميل زكي",
    },
    {
        title: "أساسيات تطوير واجهات الاستخدام باستخدام Angular",
        description: "تعلم تصميم وتطوير واجهات الاستخدام باستخدام Angular.",
        link: "https://www.udemy.com/course/angular-basics-ar/",
        category: "Web Development",
        language: "Arabic",
        cost: "Free",
        instructor: "رضا عبد الله",
    },
    {
        title: "تطوير البرمجيات باستخدام منهجية Agile",
        description: "تعلم كيفية تطبيق منهجية Agile في تطوير البرمجيات.",
        link: "https://www.udemy.com/course/agile-software-development-ar/",
        category: "Software Development",
        language: "Arabic",
        cost: "Paid",
        instructor: "أحمد الحسن",
    },
    {
        title: "تعلم البرمجة بلغة سي شارب",
        description: "احصل على مهارات البرمجة بلغة سي شارب من خلال مشاريع عملية.",
        link: "https://www.udemy.com/course/csharp-programming-ar/",
        category: "Programming",
        language: "Arabic",
        cost: "Paid",
        instructor: "خليل أسامة",
    },
    {
        title: "أساسيات تحليل البيانات باستخدام بايثون",
        description: "تعلم كيفية تحليل البيانات باستخدام بايثون.",
        link: "https://www.udemy.com/course/data-analysis-python-ar/",
        category: "Data Science",
        language: "Arabic",
        cost: "Paid",
        instructor: "فاطمة شريف",
    },
    {
        title: "تطوير تطبيقات الويب باستخدام ASP.NET",
        description: "تعلم كيفية تطوير تطبيقات الويب باستخدام ASP.NET.",
        link: "https://www.udemy.com/course/aspnet-web-development-ar/",
        category: "Web Development",
        language: "Arabic",
        cost: "Paid",
        instructor: "محمد زكي",
    },
    {
        title: "دورة متكاملة في البرمجة بلغة بايثون",
        description: "تعلم البرمجة بلغة بايثون من الصفر حتى الاحتراف.",
        link: "https://www.udemy.com/course/python-complete-course-ar/",
        category: "Programming",
        language: "Arabic",
        cost: "Paid",
        instructor: "علي حسن",
    },
    {
        title: "تصميم وتطوير مواقع الويب باستخدام HTML وCSS",
        description: "تعلم كيفية تصميم وتطوير مواقع الويب باستخدام HTML وCSS.",
        link: "https://www.udemy.com/course/html-css-web-design-ar/",
        category: "Web Development",
        language: "Arabic",
        cost: "Free",
        instructor: "فاطمة ناصر",
    },
    {
        title: "مقدمة في الشبكات",
        description: "استكشف أساسيات الشبكات وكيفية إدارتها.",
        link: "https://www.udemy.com/course/networking-basics-ar/",
        category: "Networking",
        language: "Arabic",
        cost: "Paid",
        instructor: "يوسف إدريس",
    },
    {
        title: "إدارة الوقت والفعالية الشخصية",
        description: "تعلم كيفية إدارة الوقت وزيادة الفعالية الشخصية.",
        link: "https://www.udemy.com/course/time-management-ar/",
        category: "Personal Development",
        language: "Arabic",
        cost: "Free",
        instructor: "مريم سليم",
    },
    {
        title: "أساسيات البرمجة بلغة PHP",
        description: "تعلم البرمجة بلغة PHP من خلال مشاريع عملية.",
        link: "https://www.udemy.com/course/php-basics-ar/",
        category: "Programming",
        language: "Arabic",
        cost: "Paid",
        instructor: "سارة أحمد",
    },
    {
        title: "تطوير تطبيقات الويب باستخدام فريمورك رياكت",
        description: "تعلم كيفية تطوير تطبيقات الويب باستخدام رياكت.",
        link: "https://www.udemy.com/course/react-web-development-ar/",
        category: "Web Development",
        language: "Arabic",
        cost: "Paid",
        instructor: "علياء فوزي",
    },
    {
        title: "تصميم الشعارات باستخدام Adobe Illustrator",
        description: "تعلم كيفية تصميم شعارات احترافية باستخدام Illustrator.",
        link: "https://www.udemy.com/course/logo-design-ar/",
        category: "Design",
        language: "Arabic",
        cost: "Paid",
        instructor: "محمود سعيد",
    },
    {
        title: "دورة متكاملة في البرمجة بلغة روبي",
        description: "تعلم البرمجة بلغة روبي من خلال مشاريع عملية.",
        link: "https://www.udemy.com/course/ruby-programming-ar/",
        category: "Programming",
        language: "Arabic",
        cost: "Paid",
        instructor: "عبير جمال",
    },
    {
        title: "إدارة قواعد البيانات باستخدام MySQL",
        description: "تعلم كيفية إدارة قواعد البيانات باستخدام MySQL.",
        link: "https://www.udemy.com/course/mysql-database-management-ar/",
        category: "Database Management",
        language: "Arabic",
        cost: "Free",
        instructor: "علي عبيد",
    },
    {
        title: "دورة متكاملة في الأمن السيبراني",
        description: "تعلم كيفية حماية الأنظمة والشبكات من الهجمات.",
        link: "https://www.udemy.com/course/cyber-security-complete-course-ar/",
        category: "Cybersecurity",
        language: "Arabic",
        cost: "Paid",
        instructor: "راشد القحطاني",
    },
    {
        title: "دورة تحليل البيانات باستخدام SQL",
        description: "تعلم كيفية تحليل البيانات باستخدام SQL.",
        link: "https://www.udemy.com/course/sql-data-analysis-ar/",
        category: "Data Science",
        language: "Arabic",
        cost: "Paid",
        instructor: "نور محمد",
    },
    {
        title: "أساسيات البرمجة باستخدام بايثون",
        description: "تعلم أساسيات البرمجة باستخدام بايثون مع تطبيقات عملية.",
        link: "https://www.udemy.com/course/python-basics-ar/",
        category: "Programming",
        language: "Arabic",
        cost: "Free",
        instructor: "علي الرفاعي",
    },
    {
        title: "إدارة مشاريع تكنولوجيا المعلومات",
        description: "تعلم كيفية إدارة مشاريع تكنولوجيا المعلومات بنجاح.",
        link: "https://www.udemy.com/course/it-project-management-ar/",
        category: "Project Management",
        language: "Arabic",
        cost: "Paid",
        instructor: "أمجد الحربي",
    },
    {
        title: "تطوير تطبيقات الهاتف باستخدام React Native",
        description: "تعلم كيفية بناء تطبيقات الهاتف باستخدام React Native.",
        link: "https://www.udemy.com/course/react-native-mobile-development-ar/",
        category: "Mobile App Development",
        language: "Arabic",
        cost: "Paid",
        instructor: "نادر صلاح",
    },
    {
        title: "تصميم المواقع باستخدام فريمورك Bootstrap",
        description: "تعلم كيفية تصميم مواقع الويب باستخدام فريمورك Bootstrap.",
        link: "https://www.udemy.com/course/bootstrap-web-design-ar/",
        category: "Web Development",
        language: "Arabic",
        cost: "Free",
        instructor: "فاطمة إبراهيم",
    },
    {
        title: "مقدمة في تطوير البرمجيات",
        description: "استكشف أساسيات تطوير البرمجيات والممارسات الجيدة.",
        link: "https://www.udemy.com/course/software-development-basics-ar/",
        category: "Software Development",
        language: "Arabic",
        cost: "Paid",
        instructor: "أحمد طه",
    },
    {
        title: "تعلم SQL من الصفر",
        description: "تعلم SQL من الأساسيات إلى الاحتراف.",
        link: "https://www.udemy.com/course/sql-for-beginners-ar/",
        category: "Database Management",
        language: "Arabic",
        cost: "Paid",
        instructor: "مروان علي",
    },
    {
        title: "دورة متكاملة في التحليل المالي باستخدام Excel",
        description: "تعلم كيفية تحليل البيانات المالية باستخدام Excel.",
        link: "https://www.udemy.com/course/excel-financial-analysis-ar/",
        category: "Finance",
        language: "Arabic",
        cost: "Paid",
        instructor: "يوسف سلامة",
    },
    {
        title: "دورة متكاملة في البرمجة بلغة C++",
        description: "تعلم البرمجة بلغة C++ من خلال مشاريع عملية.",
        link: "https://www.udemy.com/course/c-plus-plus-programming-ar/",
        category: "Programming",
        language: "Arabic",
        cost: "Paid",
        instructor: "رنا مصطفى",
    },
    {
        title: "تسويق المنتجات على الإنترنت",
        description: "تعلم كيفية تسويق المنتجات والخدمات عبر الإنترنت.",
        link: "https://www.udemy.com/course/online-product-marketing-ar/",
        category: "Marketing",
        language: "Arabic",
        cost: "Free",
        instructor: "سلوى مجدي",
    },
    {
        title: "أساسيات البرمجة باستخدام لغة بايثون",
        description: "استكشف المفاهيم الأساسية للبرمجة باستخدام بايثون.",
        link: "https://www.udemy.com/course/python-fundamentals-ar/",
        category: "Programming",
        language: "Arabic",
        cost: "Paid",
        instructor: "عائشة سعيد",
    },
    {
        title: "تطوير تطبيقات الويب باستخدام فريمورك Ruby on Rails",
        description: "تعلم كيفية بناء تطبيقات الويب باستخدام Ruby on Rails.",
        link: "https://www.udemy.com/course/ruby-on-rails-ar/",
        category: "Web Development",
        language: "Arabic",
        cost: "Paid",
        instructor: "أحمد عارف",
    },
    {
        title: "أساسيات الذكاء الاصطناعي",
        description: "تعلم الأساسيات والنظريات الأساسية في الذكاء الاصطناعي.",
        link: "https://www.udemy.com/course/ai-basics-ar/",
        category: "Data Science",
        language: "Arabic",
        cost: "Free",
        instructor: "سلمى عبد الله",
    },
];

export default coursesData 
