const lessonsData = {
    "responsive-web-design": {
        title: "ResponsiveWebDesign",
        status: "Not started",
        lessonsLength: 40, description: "Learn how to create websites that work on all screen sizes.",
        lessons: [
            { lesson: "Introduction to Responsive Web Design", status: "Not started" },
            { lesson: "Understanding Viewport and Media Queries", status: "Not started" },
            { lesson: "CSS Flexbox and Grid Layout", status: "Not started" },
            { lesson: "Creating Responsive Navigation Menus", status: "Not started" },
            { lesson: "Building a Mobile-First Layout", status: "Not started" },
            { lesson: "Responsive Images and Media", status: "Not started" },
            { lesson: "Using Fluid Typography", status: "Not started" },
            { lesson: "Responsive Design Patterns", status: "Not started" },
            { lesson: "Testing and Debugging Responsive Websites", status: "Not started" },
        ],
    },
    "javascript-algorithms-and-data-structures-v8": {
        title: "JavaScriptAlgorithmsAndDataStructures",
        status: "Not started",
        lessonsLength: 40, description: "Master core algorithms and data structures with JavaScript.",
        lessons: [
            { lesson: "Introduction to Algorithms and Big-O Notation", status: "Not started" },
            { lesson: "Basic Data Structures: Arrays and Objects", status: "Not started" },
            { lesson: "Sorting Algorithms: Bubble, Selection, Insertion", status: "Not started" },
            { lesson: "Advanced Sorting: Merge Sort and Quick Sort", status: "Not started" },
            { lesson: "Stacks and Queues", status: "Not started" },
            { lesson: "Linked Lists: Singly and Doubly Linked", status: "Not started" },
            { lesson: "Trees: Binary Trees and Binary Search Trees", status: "Not started" },
            { lesson: "Graph Algorithms: Depth-First and Breadth-First Search", status: "Not started" },
            { lesson: "Dynamic Programming: Memoization and Tabulation", status: "Not started" },
        ],
    },
    "data-analysis-python": {
        title: "DataAnalysisWithPython",
        status: "Not started",
        lessonsLength: 40, description: "Learn how to analyze data using Python libraries like pandas and NumPy.",
        lessons: [
            { lesson: "Introduction to Data Analysis", status: "Not started" },
            { lesson: "Working with Pandas DataFrames", status: "Not started" },
            { lesson: "Data Cleaning and Preprocessing", status: "Not started" },
            { lesson: "Exploratory Data Analysis (EDA) with Pandas", status: "Not started" },
            { lesson: "Data Visualization with Matplotlib and Seaborn", status: "Not started" },
            { lesson: "Working with Time Series Data", status: "Not started" },
            { lesson: "Handling Missing Data", status: "Not started" },
            { lesson: "Aggregating and Grouping Data", status: "Not started" },
            { lesson: "Merging and Joining DataFrames", status: "Not started" },
            { lesson: "Introduction to NumPy Arrays", status: "Not started" },
            { lesson: "Performing Statistical Analysis with Python", status: "Not started" },
        ],
    },
    "information-security-certification": {
        title: "InformationSecurity",
        status: "Not started",
        lessonsLength: 40, description: "Understand the fundamentals of information security.",
        lessons: [
            { lesson: "Introduction to Information Security", status: "Not started" },
            { lesson: "Cryptography: Basics and Types", status: "Not started" },
            { lesson: "Authentication and Authorization", status: "Not started" },
            { lesson: "Common Security Vulnerabilities", status: "Not started" },
            { lesson: "Secure Network Design", status: "Not started" },
            { lesson: "Firewalls, VPNs, and IDS/IPS", status: "Not started" },
            { lesson: "Securing Web Applications", status: "Not started" },
            { lesson: "Data Encryption Standards", status: "Not started" },
            { lesson: "Incident Response and Recovery", status: "Not started" },
            { lesson: "Security Policies and Procedures", status: "Not started" },
            { lesson: "Ethical Hacking and Penetration Testing", status: "Not started" },
        ],
    },
    "college-algebra-python": {
        title: "CollegeAlgebraWithPython",
        status: "Not started",
        lessonsLength: 40, description: "Learn algebra concepts through programming in Python.",
        lessons: [
            { lesson: "Introduction to Algebra with Python", status: "Not started" },
            { lesson: "Algebraic Expressions and Variables", status: "Not started" },
            { lesson: "Linear Equations and Inequalities", status: "Not started" },
            { lesson: "Quadratic Equations and Functions", status: "Not started" },
            { lesson: "Polynomials and Factoring", status: "Not started" },
            { lesson: "Solving Systems of Equations", status: "Not started" },
            { lesson: "Introduction to Functions and Graphs", status: "Not started" },
            { lesson: "Working with Exponential and Logarithmic Functions", status: "Not started" },
            { lesson: "Using Python to Solve Algebraic Problems", status: "Not started" },
            { lesson: "Graphing Functions with Python", status: "Not started" },
            { lesson: "Applications of Algebra in Real Life", status: "Not started" },
        ],
    },
    "csharp-foundations": {
        title: "FoundationalCSharpWithMicrosoft",
        status: "Not started",
        lessonsLength: 40, description: "Get started with the basics of C# programming.",
        lessons: [
            { lesson: "Introduction to C# Programming", status: "Not started" },
            { lesson: "Understanding Variables and Data Types", status: "Not started" },
            { lesson: "Control Flow: If, Switch, and Loops", status: "Not started" },
            { lesson: "Methods and Functions", status: "Not started" },
            { lesson: "Object-Oriented Programming (OOP) Concepts", status: "Not started" },
            { lesson: "Classes, Objects, and Inheritance", status: "Not started" },
            { lesson: "Working with Collections and Generics", status: "Not started" },
            { lesson: "Exception Handling in C#", status: "Not started" },
            { lesson: "Building Simple Applications in C#", status: "Not started" },
            { lesson: "Debugging Techniques in C#", status: "Not started" },
            { lesson: "Working with LINQ and Entity Framework", status: "Not started" },
        ],
    },
    "cloud-practitioner-essentials": {
        title: "CloudPractitionerEssentials",
        status: "Not started",
        lessonsLength: 40, description: "Learn the basics of cloud computing.",
        lessons: [
            { lesson: "Introduction to Cloud Computing", status: "Not started" },
            { lesson: "Cloud Service Models: IaaS, PaaS, SaaS", status: "Not started" },
            { lesson: "Cloud Security and Compliance", status: "Not started" },
            { lesson: "Deploying Applications on the Cloud", status: "Not started" },
            { lesson: "Understanding Cloud Storage and Databases", status: "Not started" },
            { lesson: "Monitoring and Optimizing Cloud Resources", status: "Not started" },
            { lesson: "Cost Management in the Cloud", status: "Not started" },
            { lesson: "Cloud Best Practices", status: "Not started" },
            { lesson: "Introduction to Cloud Architecture", status: "Not started" },
            { lesson: "Hands-on with Cloud Platforms", status: "Not started" },
        ],
    },
    "google-cloud-associate": {
        title: "GoogleCloudAssociate",
        status: "Not started",
        lessonsLength: 40, description: "Prepare for the Google Cloud Associate certification.",
        lessons: [
            { lesson: "Introduction to Google Cloud", status: "Not started" },
            { lesson: "Google Cloud Console and CLI", status: "Not started" },
            { lesson: "Setting Up Google Cloud Projects", status: "Not started" },
            { lesson: "Deploying Virtual Machines on Google Cloud", status: "Not started" },
            { lesson: "Managing Google Cloud Storage", status: "Not started" },
            { lesson: "Using Google Cloud Databases", status: "Not started" },
            { lesson: "Understanding Google Kubernetes Engine (GKE)", status: "Not started" },
            { lesson: "Monitoring and Logging in Google Cloud", status: "Not started" },
            { lesson: "Security Best Practices for Google Cloud", status: "Not started" },
            { lesson: "Hands-on Projects with Google Cloud", status: "Not started" },
        ],
    },
    "odin-project": {
        title: "TheOdinProject",
        status: "Not started",
        lessonsLength: 40, description: "Full-stack web development with The Odin Project.",
        lessons: [
            { lesson: "Getting Started with The Odin Project", status: "Not started" },
            { lesson: "HTML Foundations", status: "Not started" },
            { lesson: "CSS Foundations", status: "Not started" },
            { lesson: "JavaScript Foundations", status: "Not started" },
            { lesson: "Ruby on Rails Basics", status: "Not started" },
            { lesson: "Node.js and Express Basics", status: "Not started" },
            { lesson: "Database Basics with SQL", status: "Not started" },
            { lesson: "Building Projects with The Odin Project", status: "Not started" },
            { lesson: "Git and Version Control", status: "Not started" },
            { lesson: "Deployment Strategies", status: "Not started" },
            { lesson: "Full-Stack Project Development", status: "Not started" },
        ],
    },
    "coding-interview-prep": {
        title: "CodingInterviewPrep",
        status: "Not started",
        lessonsLength: 40, description: "Prepare for coding interviews with a variety of challenges.",
        lessons: [
            { lesson: "Introduction to Coding Interviews", status: "Not started" },
            { lesson: "Common Data Structures", status: "Not started" },
            { lesson: "Common Algorithms", status: "Not started" },
            { lesson: "Behavioral Interview Preparation", status: "Not started" },
            { lesson: "Mock Interview Practice", status: "Not started" },
            { lesson: "System Design Basics", status: "Not started" },
            { lesson: "Practice Problems: Arrays", status: "Not started" },
            { lesson: "Practice Problems: Strings", status: "Not started" },
            { lesson: "Practice Problems: Linked Lists", status: "Not started" },
            { lesson: "Practice Problems: Trees and Graphs", status: "Not started" },
            { lesson: "Practice Problems: Dynamic Programming", status: "Not started" },
            { lesson: "Final Interview Prep and Tips", status: "Not started" },
        ],
    },
    "project-euler": {
        title: "ProjectEuler",
        status: "Not started",
        lessonsLength: 40, description: "Solve challenging math and programming problems.",
        lessons: [
            { lesson: "Introduction to Project Euler", status: "Not started" },
            { lesson: "Problem Solving Strategies", status: "Not started" },
            { lesson: "Mathematical Concepts in Programming", status: "Not started" },
            { lesson: "Optimizing Algorithms for Performance", status: "Not started" },
            { lesson: "Using Python for Problem Solving", status: "Not started" },
            { lesson: "Exploring Number Theory", status: "Not started" },
            { lesson: "Working with Prime Numbers", status: "Not started" },
            { lesson: "Calculating Fibonacci Numbers", status: "Not started" },
            { lesson: "Understanding Recursion", status: "Not started" },
            { lesson: "Final Project Euler Challenges", status: "Not started" },
        ],
    },
    "rosetta-code": {
        title: "RosettaCode",
        status: "Not started",
        lessonsLength: 40, description: "Learn programming through example solutions to common tasks.",
        lessons: [
            { lesson: "Introduction to Rosetta Code", status: "Not started" },
            { lesson: "Understanding Code Examples", status: "Not started" },
            { lesson: "Translating Algorithms Between Languages", status: "Not started" },
            { lesson: "Exploring Different Programming Paradigms", status: "Not started" },
            { lesson: "Working with Popular Algorithms", status: "Not started" },
            { lesson: "Using Rosetta Code for Learning", status: "Not started" },
            { lesson: "Collaborating on Code Examples", status: "Not started" },
            { lesson: "Contributing to Rosetta Code", status: "Not started" },
            { lesson: "Building a Portfolio with Rosetta Code", status: "Not started" },
            { lesson: "Final Projects Using Rosetta Code Examples", status: "Not started" },
        ],
    },
    "explore-legacy-curriculum": {
        title: "ExploreLegacyCurriculum",
        status: "Not started",
        lessonsLength: 40, description: "Dive into the legacy curriculum of coding challenges.",
        lessons: [
            { lesson: "Introduction to Legacy Curriculum", status: "Not started" },
            { lesson: "Understanding Legacy Algorithms", status: "Not started" },
            { lesson: "Exploring Classic Data Structures", status: "Not started" },
            { lesson: "Solving Legacy Coding Challenges", status: "Not started" },
            { lesson: "Building Projects with Legacy Concepts", status: "Not started" },
            { lesson: "Refactoring Legacy Code", status: "Not started" },
            { lesson: "Best Practices in Legacy Development", status: "Not started" },
            { lesson: "Modernizing Legacy Applications", status: "Not started" },
            { lesson: "Final Projects with Legacy Curriculum", status: "Not started" },
            { lesson: "Legacy Code vs Modern Code", status: "Not started" },
        ],
    },
    "legacy-responsive-web-design": {
        title: "LegacyResponsiveWebDesign",
        status: "Not started",
        lessonsLength: 40, description: "Review the foundations of responsive web design.",
        lessons: [
            { lesson: "Introduction to Legacy Responsive Design", status: "Not started" },
            { lesson: "Understanding Old vs. New Practices", status: "Not started" },
            { lesson: "Classic CSS Techniques for Responsiveness", status: "Not started" },
            { lesson: "Building Legacy Websites", status: "Not started" },
            { lesson: "Reviewing Older Responsive Frameworks", status: "Not started" },
            { lesson: "Testing Legacy Websites on Different Devices", status: "Not started" },
            { lesson: "Comparing Legacy and Current Practices", status: "Not started" },
            { lesson: "Final Projects Using Legacy Techniques", status: "Not started" },
            { lesson: "Challenges in Legacy Responsive Design", status: "Not started" },
        ],
    },
    "legacy-javascript-algorithms": {
        title: "LegacyJavaScriptAlgorithms",
        status: "Not started",
        lessonsLength: 40, description: "Explore classic algorithms using JavaScript.",
        lessons: [
            { lesson: "Introduction to Legacy JavaScript Algorithms", status: "Not started" },
            { lesson: "Classic Sorting Algorithms", status: "Not started" },
            { lesson: "Legacy Search Algorithms", status: "Not started" },
            { lesson: "Understanding Recursion in Legacy Code", status: "Not started" },
            { lesson: "Working with Classic Data Structures", status: "Not started" },
            { lesson: "Building Projects with Legacy Algorithms", status: "Not started" },
            { lesson: "Refactoring Legacy Algorithms for Modern Use", status: "Not started" },
            { lesson: "Comparing Legacy and Modern Algorithms", status: "Not started" },
            { lesson: "Final Projects Using Legacy JavaScript", status: "Not started" },
        ],
    },
    "legacy-python-for-everybody": {
        title: "LegacyPythonForEverybody",
        status: "Not started",

        lessonsLength: 40, description: "Review foundational Python concepts.",
        lessons: [
            { lesson: "Introduction to Legacy Python for Everybody", status: "Not started" },
            { lesson: "Basic Syntax and Data Types", status: "Not started" },
            { lesson: "Control Flow and Functions", status: "Not started" },
            { lesson: "Working with Lists and Dictionaries", status: "Not started" },
            { lesson: "Introduction to Object-Oriented Programming", status: "Not started" },
            { lesson: "File Handling in Python", status: "Not started" },
            { lesson: "Building Simple Projects in Python", status: "Not started" },
            { lesson: "Exploring Python Libraries", status: "Not started" },
            { lesson: "Comparing Legacy Python and Modern Python", status: "Not started" },
            { lesson: "Final Projects Using Legacy Python", status: "Not started" },
        ],
    },
};

export default lessonsData;
